<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="112662" started-at="2018-12-19T12:06:01Z" finished-at="2018-12-19T12:07:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="112662" started-at="2018-12-19T12:06:01Z" finished-at="2018-12-19T12:07:54Z">
      <class name="com.hub.TestNGscript.HubTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02]" name="beforeMethod" is-config="true" duration-ms="25557" started-at="2018-12-19T17:36:01Z" finished-at="2018-12-19T17:36:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="Signin(java.lang.String, java.lang.String)[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02]" name="Signin" duration-ms="533" started-at="2018-12-19T17:36:28Z" data-provider="Test" finished-at="2018-12-19T17:36:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mycallcenter2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Samsung888@]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signin -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02]" name="afterMethod" is-config="true" duration-ms="16" started-at="2018-12-19T17:36:28Z" finished-at="2018-12-19T17:36:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Signin status=SUCCESS method=HubTest.Signin(java.lang.String, java.lang.String)[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="Myevent2()[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02]" name="Myevent2" duration-ms="85358" started-at="2018-12-19T17:36:28Z" finished-at="2018-12-19T17:37:54Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.hub.TestNGscript.HubTest.Myevent2(HubTest.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Myevent2 -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02]" name="endReport" is-config="true" duration-ms="93" started-at="2018-12-19T17:37:54Z" finished-at="2018-12-19T17:37:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-12-19T17:37:54Z" finished-at="2018-12-19T17:37:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Myevent2 status=FAILURE method=HubTest.Myevent2()[pri:0, instance:com.hub.TestNGscript.HubTest@457e2f02] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.hub.TestNGscript.HubTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
